monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*hdmi.*"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S16LE"
        audio.rate = 48000
        api.alsa.period-size = 2048
        api.alsa.headroom = 1024
      }
    }
  }
]
